### ISSUE TITLE
Latest DRF and Django does not work

### ISSUE THREAD

**Issue by tarsil** [vbabiy/djangorestframework-camel-case#96]
So I was trying to run this with all parsers and so on but I encountered this

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 263, in _get_response_async
    response = await sync_to_async(response.render, thread_sensitive=True)()
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/local/lib/python3.8/dist-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.8/dist-packages/djangorestframework_camel_case/render.py", line 16, in render
    return super(CamelCaseBrowsableAPIRenderer, self).render(
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/renderers.py", line 692, in get_context
    'available_formats': [renderer_cls.format for renderer_cls in view.renderer_classes],
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/renderers.py", line 692, in <listcomp>
    'available_formats': [renderer_cls.format for renderer_cls in view.renderer_classes],
AttributeError: type object 'MultiPartParser' has no attribute 'format'
```

This is due the latest DRF and this breaks all over the place

**Comment by vbabiy** [comment]
@tarsil please try with the new version.
